### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by hardikshah91** [nuxt-community/axios-module#152]
I'm using [Nuxt-axios][1] module with the proxy.

For Error handling, I have common code in

**Plugins/axios.js**

    export default function({ $axios, __isRetryRequest, store, app, redirect , payload , next}) {
      $axios.onRequest(config => {
      if (app.$cookies.get('at') && app.$cookies.get('rt') && config.url != '/post_login/') {
          config.headers.common['Authorization'] = `Bearer ${app.$cookies.get('at')}`;
        }
      });
    
      $axios.onResponseError(err => {
        const code = parseInt(err.response && err.response.status)
    
        let originalRequest = err.config;
    
        if (code === 401) {
          originalRequest.__isRetryRequest = true;
    
          store
            .dispatch('LOGIN', { grant_type: 'refresh_token', refresh_token: app.$cookies.get('rt')})
            .then(res => {
              originalRequest.headers['Authorization'] = 'Bearer ' + app.$cookies.get('at');
              return app.$axios(originalRequest);
            })
            .catch(error => {
              console.log(error);
            });
        }
    
        // code for 422 error
        if (code == 422) {
          throw err.response;
        }
        
      });
    }

On my page folder index page

**Pages/index.vue**

    <template>
      <section>Component data</section>
    </template>
    
    <script type="text/javascript">
    export default {
      async asyncData({ route, store }) {
        await store.dispatch('GET_BANNERS');
      }
    }
    </script>

All the API calls are in a stroes/actions.js file.

Now the question is when I refresh the page index.vue first API request will hit and get the response if successful. But now if on first request( 'GET_BANNERS' ) from asyncData and it gets 401 error unauthorized then I'm getting below error

    Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

how can I resolve this?

**few more questions:**

1) When I'm writing common error code in axios, original request on which I have received 401 how can I set data to store again(which we normally do from actions file)?

2) can anyone help with best practice to attach authorization headers and error handle for 400,401,422, etc..
  
  [1]: https://axios.nuxtjs.org/

**Comment by hardikshah91** [comment]
@pi0 @Atinux  Can you guys help!!!!

**Comment by hardikshah91** [comment]
fixed

**Comment by unr** [comment]
@hardikshah91 What did you do to solve this?

I'm still seeing this issue in my own projects.

**Comment by hardikshah91** [comment]
@unr Fixed with same code with some modification.
please share your code will try to debug.

**Comment by hardikshah91** [comment]
@unr below is Solution which is working for me. For 401
```
        originalRequest.__isRetryRequest = true;
        let token = cookies.get('token');

        return new Promise((resolve, reject) => {
          let req = $axios
            .post(`/login`, { grant_type: 'refresh_token', refresh_token: token })
            .then((response) => {
              if (response.status == 200) {
                store.commit('Login/SET_USER', response.data);
              }
              resolve(req);
            })
            .catch((e) => {
              reject(e);
            });
        })
          .then((res) => {
            return $axios(originalRequest);
          })
          .catch((e) => {
            throw e;
          });
```
