### ISSUE TITLE
isAxiosError is undefined on NuxtAxiosInstance

### ISSUE THREAD

**Issue by BobbieGoede** [nuxt-community/axios-module#550]
`NuxtAxiosInstance` does not have `isAxiosError` while the interface it extends suggest that it does.

**Comment by silverbackdan** [comment]
It should do - perhaps you are not importing the type properly? There was an issue I had which is resolved here, fancy taking a look as if it resolves your issue you can close this one? https://github.com/nuxt-community/axios-module/issues/555

**Comment by ZhuBoao** [comment]
> 

No, seems like it `isAxiosError` functions still doesn't exist on `NuxtAxiosInstance`. At least not on latest release `5.13.6`.

**Comment by silverbackdan** [comment]
Ah yes, misunderstood the issue and you're right, hopefully maintainers will see your fix :)
